export const neetSubjects = ["physics", "chemistry", "zoology", "botany", "mental-ability-test"];

export const neetData = {

  physics: [

    // From book 1 
    { id: "phy-ch1", chapterName: "Rotational Motion" },
    { id: "phy-ch2", chapterName: "Periodic Motion" },
    { id: "phy-ch3", chapterName: "Fluid Statics" },
    { id: "phy-ch4", chapterName: "Surface Tension" },
    { id: "phy-ch5", chapterName: "Fluid Dynamics" },
    { id: "phy-ch6", chapterName: "Thermodynamics" },
    { id: "phy-ch7", chapterName: "Wave Motion" },
    { id: "phy-ch8", chapterName: "Mechanical Wave" },
    { id: "phy-ch9", chapterName: "Waves in Pipes and Strings" },
    { id: "phy-ch10", chapterName: "Acoustic Phenomenon" },
    { id: "phy-ch11", chapterName: "Nature and Propagation of Light" },
    { id: "phy-ch12", chapterName: "Wave Optics" },
    { id: "phy-ch13", chapterName: "Electrical Cicuit" },
    { id: "phy-ch14", chapterName: "Thermo Electric Effect" },
    { id: "phy-ch15", chapterName: "Magnetic Field" },
    { id: "phy-ch16", chapterName: "Magnetic Property of Material" },
    { id: "phy-ch17", chapterName: "EMI" },
    { id: "phy-ch18", chapterName: "Alternating Current" },
    { id: "phy-ch19", chapterName: "Modern Physics" },
    { id: "phy-ch20", chapterName: "Quantization of Energy" },
    { id: "phy-ch21", chapterName: "RadioActivity" },
    { id: "phy-ch22", chapterName: "Recent Trend in Physics" },

    // from book 2
    { id: "phy-ch23", chapterName: "Physical Quantity" },
    { id: "phy-ch24", chapterName: "Vectors" },
    { id: "phy-ch25", chapterName: "Kinematics" },
    { id: "phy-ch26", chapterName: "Dynamics" },
    { id: "phy-ch27", chapterName: "Work, Energy and Power" },
    { id: "phy-ch28", chapterName: "Circulor Motion" },
    { id: "phy-ch29", chapterName: "Gravitation" },
    { id: "phy-ch30", chapterName: "Elasticity" },
    { id: "phy-ch31", chapterName: "Heat and Temperature" },
    { id: "phy-ch32", chapterName: "Thermal Expansion" },
    { id: "phy-ch33", chapterName: "Rate of Heat Flow" },
    { id: "phy-ch34", chapterName: "Thermal Properties of Matter" },
    { id: "phy-ch35", chapterName: "Ideal Gas" },
    { id: "phy-ch36", chapterName: "Ray Optics" },
    { id: "phy-ch37", chapterName: "Electrostatics" },
    { id: "phy-ch38", chapterName: "Electricity" },
    { id: "phy-ch39", chapterName: "Nuclear Physics" },
    { id: "phy-ch40", chapterName: "Semiconductor" },
  ],

  chemistry: [
    // Physical Chemistry (Unit 1)
    { id: "chem-ch1", chapterName: "Volumetric Analysis", unit: "Physical Chemistry" },
    { id: "chem-ch2", chapterName: "Ionic Equilibrium", unit: "Physical Chemistry" },
    { id: "chem-ch3", chapterName: "Chemical Kinetics", unit: "Physical Chemistry" },
    { id: "chem-ch4", chapterName: "Chemical Thermodynamics", unit: "Physical Chemistry" },
    { id: "chem-ch5", chapterName: "Electrochemistry", unit: "Physical Chemistry" },
    { id: "chem-ch6", chapterName: "Foundation and Fundamental", unit: "Physical Chemistry" },
    { id: "chem-ch7", chapterName: "Stoichiometry", unit: "Physical Chemistry" },
    { id: "chem-ch8", chapterName: "Atomic Structure", unit: "Physical Chemistry" },
    { id: "chem-ch9", chapterName: "Periodic Table", unit: "Physical Chemistry" },
    { id: "chem-ch10", chapterName: "Chemical Bonding and Shapes of Molecules", unit: "Physical Chemistry" },
    { id: "chem-ch11", chapterName: "Oxidation and Reduction", unit: "Physical Chemistry" },
    { id: "chem-ch12", chapterName: "States of Matter", unit: "Physical Chemistry" },
    { id: "chem-ch13", chapterName: "Chemical Equilibrium", unit: "Physical Chemistry" },

    // Organic Chemistry (Unit 2)
    { id: "chem-ch14", chapterName: "Haloalkanes & Haloarenes", unit: "Organic Chemistry" },
    { id: "chem-ch15", chapterName: "Alcohol", unit: "Organic Chemistry" },
    { id: "chem-ch16", chapterName: "Phenol", unit: "Organic Chemistry" },
    { id: "chem-ch17", chapterName: "Ether", unit: "Organic Chemistry" },
    { id: "chem-ch18", chapterName: "Aldehydes and ketones", unit: "Organic Chemistry" },
    { id: "chem-ch19", chapterName: "Carboxylic Acids and Its Derivatives", unit: "Organic Chemistry" },
    { id: "chem-ch20", chapterName: "Nitro Compounds", unit: "Organic Chemistry" },
    { id: "chem-ch21", chapterName: "Amino Coumpounds", unit: "Organic Chemistry" },
    { id: "chem-ch22", chapterName: "Organometallic Compounds", unit: "Organic Chemistry" },
    { id: "chem-ch23", chapterName: "Basic Concept of Organic Chemistry", unit: "Organic Chemistry" },
    { 
      id: "chem-ch24", 
      chapterName: "Fundamental Principles of Organic Chemistry", 
      unit: "Organic Chemistry",
      subtopics: [
        { id: "chem-ch24-st1", name: "Nomenclature" },
        { id: "chem-ch24-st2", name: "Isomerism" },
        { id: "chem-ch24-st3", name: "Reaction Mechanism" },
        { id: "chem-ch24-st4", name: "Detection of Heteroelements" }
      ]
    },
    {
       id: "chem-ch25", 
       chapterName: "Hydrocarbons", 
       unit: "Organic Chemistry",
       subtopics:[
        {id:"chem-ch25-st-1", name:"Alkane"},
        {id:"chem-ch25-st-2", name:"Alkene"},
        {id:"chem-ch25-st-3", name:"Alkyne"},
       ]
    },
    { id: "chem-ch26", chapterName: "Aromatic Hydrocarbon", unit: "Organic Chemistry" },

    // Inorganic Chemistry (Unit 3)
    { id: "chem-ch27", chapterName: "Transition Metals", unit: "Inorganic Chemistry" },
    {
       id: "chem-ch28", 
       chapterName: "Studies of Heavy Metals", unit: "Inorganic Chemistry",
       subtopics:[
        {id:"chem-ch28-st1", name:"Copper"}, 
        {id:"chem-ch28-st2", name:"Zinc"}, 
        {id:"chem-ch28-st3", name:"Mercury"}, 
        {id:"chem-ch28-st4", name:"Iron"}, 
        {id:"chem-ch28-st5", name:"Silver"}, 
       ]
    },
    {
       id: "chem-ch29", 
       chapterName: "Non-Metals", 
       unit: "Inorganic Chemistry",
       subtopics:[
        {id:"chem-ch29-st1", name:"Hydrogen"},
        {id:"chem-ch29-st2", name:"Oxygen and Ozone"},
        {id:"chem-ch29-st3", name:"Nitrogen"},
        {id:"chem-ch29-st4", name:"Halogen"},
        {id:"chem-ch29-st5", name:"Carbon"},
        {id:"chem-ch29-st6", name:"Phosphorus"},
        {id:"chem-ch29-st7", name:"Sulphur and its Compounds"},
       ]
    },
    { 
      id: "chem-ch30", 
      chapterName: "Metals", 
      unit: "Inorganic Chemistry",
      subtopics:[
        {id:"chem-30-st1", name:"Metallurgy"},
        {id:"chem-30-st2", name:"Alkali Metals"},
        {id:"chem-30-st3", name:"Alkaline Earth Meral"},
      ]
    },
    { id: "chem-ch31", chapterName: "Bio-Inorganic Chemistry", unit: "Inorganic Chemistry" },


    // Applied Chemistry (Unit 4)
    { id: "chem-ch32", chapterName: "Cement", unit: "Applied Chemistry" },
    { id: "chem-ch33", chapterName: "Paper and Pulp", unit: "Applied Chemistry" },
    { id: "chem-ch34", chapterName: "Nuclear Chemistry and Application of ratioactivity", unit: "Applied Chemistry" },
    { id: "chem-ch35", chapterName: "Polymers, Dyes and Drugs", unit: "Applied Chemistry" },
    { id: "chem-ch36", chapterName: "Fundamentals of Applied Chemistry", unit: "Applied Chemistry" },
    { id: "chem-ch37", chapterName: "Modern Chemical Manufactures", unit: "Applied Chemistry" },
  ],

  zoology: [
    { id: "zoo-ch1", chapterName: "Biology" },
    { id: "zoo-ch2", chapterName: "Classification of Animals" },
    { id: "zoo-ch3", chapterName: "Protistan Protozoa" },
    { id: "zoo-ch4", chapterName: "Protozoology" },
    { id: "zoo-ch5", chapterName: "Porifera" },
    { id: "zoo-ch6", chapterName: "Coelenterata" },
    { id: "zoo-ch7", chapterName: "Cnidology" },
    { id: "zoo-ch8", chapterName: "Platyhelminthes" },
    { id: "zoo-ch9", chapterName: "Helminthology (Flatworm)" },
    { id: "zoo-ch10", chapterName: "Aschelminthes" },
    { id: "zoo-ch11", chapterName: "Helminthology (Roundworm)" },
    { id: "zoo-ch12", chapterName: "Annelida" },
    { id: "zoo-ch13", chapterName: "Arthropoda" },
    { id: "zoo-ch14", chapterName: "Entomology" },
    { id: "zoo-ch15", chapterName: "Mollusca" },
    { id: "zoo-ch16", chapterName: "Echinodermata" },
    { id: "zoo-ch17", chapterName: "Hemichordata" },
    { id: "zoo-ch18", chapterName: "Chordata" },
    { id: "zoo-ch19", chapterName: "Plasmodium" },
    { id: "zoo-ch20", chapterName: "Pheretima Posthuma" },
    { id: "zoo-ch21", chapterName: "Rana Tigrina" },
    { id: "zoo-ch22", chapterName: "Life Components" },
    { id: "zoo-ch23", chapterName: "Life and its Origin" },
    { id: "zoo-ch24", chapterName: "Evolution" },
    { id: "zoo-ch25", chapterName: "Evidences of Organic Evolution" },
    { id: "zoo-ch26", chapterName: "Human Evolution" },
    { id: "zoo-ch27", chapterName: "Animal Adaptations" },
    { id: "zoo-ch28", chapterName: "Animal Behaviour" },
    { id: "zoo-ch29", chapterName: "Environmental Issues" },
    { id: "zoo-ch30", chapterName: "Animal Tissues" },
    { id: "zoo-ch31", chapterName: "Human Digestive System" },
    { id: "zoo-ch32", chapterName: "Human Respiratory System" },
    { id: "zoo-ch33", chapterName: "Human Excretory System" },
    { id: "zoo-ch34", chapterName: "Human Circulatory System" },
    { id: "zoo-ch35", chapterName: "Human Nervous System" },
    { id: "zoo-ch36", chapterName: "Human Endocrine System" },
    { id: "zoo-ch37", chapterName: "Human Sensory Organ" },
    { id: "zoo-ch38", chapterName: "Human Reproductive System" },
    { id: "zoo-ch39", chapterName: "Developmental Biology" },
    { id: "zoo-ch40", chapterName: "Embryonic Development in Human" },
    { id: "zoo-ch41", chapterName: "Development of Frog" },
    { id: "zoo-ch42", chapterName: "Common Human Diseases" },
    { id: "zoo-ch43", chapterName: "Drug Abuse" },
    { id: "zoo-ch44", chapterName: "Immune System" },
    { id: "zoo-ch45", chapterName: "Application of Zoology" },
    { id: "zoo-ch46", chapterName: "Test Tube Baby" },
    { id: "zoo-ch47", chapterName: "Organ Transplant" },
    { id: "zoo-ch48", chapterName: "Vaccine" },
  ],

  botany: [
    { id: "bot-ch1", chapterName: "Taxonomy and Systematics" },
    { id: "bot-ch2", chapterName: "Virus" },
    { id: "bot-ch3", chapterName: "Kingdom Monera / Bacteria" },
    { id: "bot-ch4", chapterName: "Kingdom Fungi and Lichen" },
    { id: "bot-ch5", chapterName: "Introduction to Plant Kingdom" },
    { id: "bot-ch6", chapterName: "Algae" },
    { id: "bot-ch7", chapterName: "Bryophytes" },
    { id: "bot-ch8", chapterName: "Pteridophytes" },
    { id: "bot-ch9", chapterName: "Gymnosperm" },
    { id: "bot-ch10", chapterName: "Morphology of Angiosperm" },
    { id: "bot-ch11", chapterName: "Families of Angiosperms" },
    { id: "bot-ch12", chapterName: "Organism and Population" },
    { id: "bot-ch13", chapterName: "Eco System and Succession" },
    { id: "bot-ch14", chapterName: "Ecological Adaptations and Environmental Issues" },
    { id: "bot-ch15", chapterName: "Vegetation" },
    { id: "bot-ch16", chapterName: "Tools to Cytology and Biomolecules" },
    { id: "bot-ch17", chapterName: "Cytology" },
    { id: "bot-ch18", chapterName: "Cell Cycle and Cell Division" },
    { id: "bot-ch19", chapterName: "Mendelian Genetics (Basis of Inheritance)" },
    { id: "bot-ch20", chapterName: "Chromosomal Basis of Inheritance (Linkage and Sex Linked Inheritance)" },
    { id: "bot-ch21", chapterName: "Molecular Basis of Inheritance" },
    { id: "bot-ch22", chapterName: "Plant Anatomy" },
    { id: "bot-ch23", chapterName: "Plant Water Relation / Transport in Plant / Mineral Nutrition" },
    { id: "bot-ch24", chapterName: "Plant Photosynthesis" },
    { id: "bot-ch25", chapterName: "Plant Respiration" },
    { id: "bot-ch26", chapterName: "Plant Hormones" },
    { id: "bot-ch27", chapterName: "Plant Growth and Movements" },
    { id: "bot-ch28", chapterName: "Sexual Reproduction in Angiosperms / Embryology" },
    { id: "bot-ch29", chapterName: "Biotechnology" },
  ],

  "mental-ability-test": [

    // Unit 1: Numerical Reasoning
    { id: "mat-ch1", chapterName: "Percentage" },
    { id: "mat-ch2", chapterName: "Profit and Loss" },
    { id: "mat-ch3", chapterName: "Time and Work" },
    { id: "mat-ch4", chapterName: "Date and Calendar" },
    { id: "mat-ch5", chapterName: "Average" },
    { id: "mat-ch6", chapterName: "Ratio and Proportion" },
    { id: "mat-ch7", chapterName: "Problem on Age" },
    { id: "mat-ch8", chapterName: "Clock" },
    { id: "mat-ch9", chapterName: "Simple & Compound Interest" },
    { id: "mat-ch10", chapterName: "Partnership" },

    // Unit 2: Verbal Reasoning
    { id: "mat-ch11", chapterName: "Direction and Distance" },
    { id: "mat-ch12", chapterName: "Coding-Decoding" },
    { id: "mat-ch13", chapterName: "Ranking Order" },
    { id: "mat-ch14", chapterName: "Blood Relation" },
    { id: "mat-ch15", chapterName: "Verbal Puzzle" },
    { id: "mat-ch16", chapterName: "Cause and Effect" },
    { id: "mat-ch17", chapterName: "Assertion and Reason" },
    { id: "mat-ch18", chapterName: "Statement and Conclusion" },
    { id: "mat-ch19", chapterName: "Statement and Assumption" },
    { id: "mat-ch20", chapterName: "Statement and Argument" },
    { id: "mat-ch21", chapterName: "Situation Reaction Test" },

    // Unit 3: Logical Reasoning
    { id: "mat-ch22", chapterName: "Number Series" },
    { id: "mat-ch23", chapterName: "Verbal Series" },
    { id: "mat-ch24", chapterName: "Number Analogy" },
    { id: "mat-ch25", chapterName: "Verbal Analogy" },
    { id: "mat-ch26", chapterName: "Number Classification" },
    { id: "mat-ch27", chapterName: "Verbal Classification" },
    { id: "mat-ch28", chapterName: "Matrix & Missing Character" },
    { id: "mat-ch29", chapterName: "Logical Sequencing of Words" },
    { id: "mat-ch30", chapterName: "Continuous Pattern" },
    { id: "mat-ch31", chapterName: "Common Properties" },
    { id: "mat-ch32", chapterName: "Venn Diagram" },
    { id: "mat-ch33", chapterName: "Arithmetical Reasoning" },

    // Unit 4: Abstract Reasoning
    { id: "mat-ch34", chapterName: "Figure Series" },
    { id: "mat-ch35", chapterName: "Figure Analogy" },
    { id: "mat-ch36", chapterName: "Figure Classification" },
    { id: "mat-ch37", chapterName: "Figure Matrix" },
    { id: "mat-ch38", chapterName: "Paper Folding" },
    { id: "mat-ch39", chapterName: "Paper Cutting" },
    { id: "mat-ch40", chapterName: "Embedded Figure" },
    { id: "mat-ch41", chapterName: "Dot Situation" },
    { id: "mat-ch42", chapterName: "Cube and Dice" },
    { id: "mat-ch43", chapterName: "Mirror Image" },
    { id: "mat-ch44", chapterName: "Water Image" },
    { id: "mat-ch45", chapterName: "Pattern Completion" },
    { id: "mat-ch46", chapterName: "Figure Formation" },
    { id: "mat-ch47", chapterName: "Construction of Square & Triangle" },
    { id: "mat-ch48", chapterName: "Analytical Reasoning" },
  ],
};

export function getSubjectDisplayName(subject) {
  const nameMap = {
    physics: "Physics",
    chemistry: "Chemistry",
    zoology: "Zoology",
    botany: "Botany",
    "mental-ability-test": "Mental Ability Test",
  };
  return nameMap[subject] || subject.charAt(0).toUpperCase() + subject.slice(1);
}