export const neetSubjects = ["physics", "chemistry", "zoology", "botany", "mental-ability-test"];

export const neetData = {
  physics: [
    // From phy1 (1–12 same)
    { id: "phy-ch1", chapterName: "Rotational Motion" },
    { id: "phy-ch2", chapterName: "Periodic Motion" },
    { id: "phy-ch3", chapterName: "Fluid Statics" },
    { id: "phy-ch4", chapterName: "Surface Tension" },
    { id: "phy-ch5", chapterName: "Fluid Dynamics" },
    { id: "phy-ch6", chapterName: "Thermodynamics" },
    { id: "phy-ch7", chapterName: "Thermodynamics" },
    { id: "phy-ch8", chapterName: "Wave Motion" },
    { id: "phy-ch9", chapterName: "Mechanical Wave" },
    { id: "phy-ch10", chapterName: "Waves in Pipes and Strings" },
    { id: "phy-ch11", chapterName: "Acoustic Phenomenon" },
    { id: "phy-ch12", chapterName: "Nature and Propagation of Light" },

    // 13–17 → Ray Optics
    { id: "phy-ch13", chapterName: "Ray Optics" },
    { id: "phy-ch14", chapterName: "Ray Optics" },
    { id: "phy-ch15", chapterName: "Ray Optics" },
    { id: "phy-ch16", chapterName: "Ray Optics" },
    { id: "phy-ch17", chapterName: "Ray Optics" },

    // From phy1 continuation
    { id: "phy-ch18", chapterName: "Electrostatics" },
    { id: "phy-ch19", chapterName: "Electricity" },
    { id: "phy-ch20", chapterName: "Nuclear Physics" },
    { id: "phy-ch21", chapterName: "Semiconductor" },

    // From phy3 (Class 11 alternate structure)
    // 1–5 same but continuing numbering
    { id: "phy-ch22", chapterName: "Physical Quantity" },
    { id: "phy-ch23", chapterName: "Vectors" },
    { id: "phy-ch24", chapterName: "Kinematics" },
    { id: "phy-ch25", chapterName: "Dynamics" },
    { id: "phy-ch26", chapterName: "Work, Energy and Power" },

    // 6–7 → Thermodynamics
    { id: "phy-ch27", chapterName: "Thermodynamics" },
    { id: "phy-ch28", chapterName: "Thermodynamics" },

    // 8–12 same
    { id: "phy-ch29", chapterName: "Wave Motion" },
    { id: "phy-ch30", chapterName: "Mechanical Wave" },
    { id: "phy-ch31", chapterName: "Waves in Pipes and Strings" },
    { id: "phy-ch32", chapterName: "Acoustic Phenomenon" },
    { id: "phy-ch33", chapterName: "Nature and Propagation of Light" },

    // 13–15 → Wave Optics
    { id: "phy-ch34", chapterName: "Wave Optics" },
    { id: "phy-ch35", chapterName: "Wave Optics" },
    { id: "phy-ch36", chapterName: "Wave Optics" },

    // 16–18 same
    { id: "phy-ch37", chapterName: "Electrical Circuits" },
    { id: "phy-ch38", chapterName: "Thermoelectric Effects" },
    { id: "phy-ch39", chapterName: "Magnetic Field" },

    // Remaining from phy2 & phy4 (Class 12 continuation)
    { id: "phy-ch40", chapterName: "Magnetic Properties of Materials" },
    { id: "phy-ch41", chapterName: "Electromagnetic Induction" },
    { id: "phy-ch42", chapterName: "Alternating Current" },
    { id: "phy-ch43", chapterName: "Electrons" },
    { id: "phy-ch44", chapterName: "Photons" },
    { id: "phy-ch45", chapterName: "Semiconductor Devices" },
    { id: "phy-ch46", chapterName: "Quantization of Energy" },
    { id: "phy-ch47", chapterName: "Radioactivity" },
    { id: "phy-ch48", chapterName: "Recent Trend in Physics" },
  ],

  chemistry: [
    { id: "chem-ch1", chapterName: "Some Basic Concepts of Chemistry" },
    { id: "chem-ch2", chapterName: "Structure of Atom" },
    { id: "chem-ch3", chapterName: "States of Matter" },
    { id: "chem-ch4", chapterName: "Chemical Thermodynamics" },
    { id: "chem-ch5", chapterName: "Solutions" },
    { id: "chem-ch6", chapterName: "Equilibrium" },
    { id: "chem-ch7", chapterName: "Redox Reactions and Electrochemistry" },
    { id: "chem-ch8", chapterName: "Chemical Kinetics" },
    { id: "chem-ch9", chapterName: "Surface Chemistry" },
    { id: "chem-ch10", chapterName: "Periodic Table" },
    { id: "chem-ch11", chapterName: "Chemical Bonding" },
    { id: "chem-ch12", chapterName: "Hydrogen" },
    { id: "chem-ch13", chapterName: "s-Block Elements" },
    { id: "chem-ch14", chapterName: "p-Block Elements" },
    { id: "chem-ch15", chapterName: "d & f Block Elements" },
    { id: "chem-ch16", chapterName: "Coordination Compounds" },
    { id: "chem-ch17", chapterName: "Organic Basics" },
    { id: "chem-ch18", chapterName: "Hydrocarbons" },
    { id: "chem-ch19", chapterName: "Halo Compounds" },
    { id: "chem-ch20", chapterName: "Alcohols & Ethers" },
    { id: "chem-ch21", chapterName: "Amines" },
    { id: "chem-ch22", chapterName: "Biomolecules" },
  ],

  zoology: [
    { id: "zoo-ch1", chapterName: "Biology" },
    { id: "zoo-ch2", chapterName: "Classification of Animals" },
    { id: "zoo-ch3", chapterName: "Protistan Protozoa" },
    { id: "zoo-ch4", chapterName: "Protozoology" },
    { id: "zoo-ch5", chapterName: "Porifera" },
    { id: "zoo-ch6", chapterName: "Coelenterata" },
    { id: "zoo-ch7", chapterName: "Cnidology" },
    { id: "zoo-ch8", chapterName: "Platyhelminthes" },
    { id: "zoo-ch9", chapterName: "Helminthology (Flatworm)" },
    { id: "zoo-ch10", chapterName: "Aschelminthes" },
    { id: "zoo-ch11", chapterName: "Helminthology (Roundworm)" },
    { id: "zoo-ch12", chapterName: "Annelida" },
    { id: "zoo-ch13", chapterName: "Arthropoda" },
    { id: "zoo-ch14", chapterName: "Entomology" },
    { id: "zoo-ch15", chapterName: "Mollusca" },
    { id: "zoo-ch16", chapterName: "Echinodermata" },
    { id: "zoo-ch17", chapterName: "Hemichordata" },
    { id: "zoo-ch18", chapterName: "Chordata" },
    { id: "zoo-ch19", chapterName: "Plasmodium" },
    { id: "zoo-ch20", chapterName: "Pheretima Posthuma" },
    { id: "zoo-ch21", chapterName: "Rana Tigrina" },
    { id: "zoo-ch22", chapterName: "Life Components" },
    { id: "zoo-ch23", chapterName: "Life and its Origin" },
    { id: "zoo-ch24", chapterName: "Evolution" },
    { id: "zoo-ch25", chapterName: "Evidences of Organic Evolution" },
    { id: "zoo-ch26", chapterName: "Human Evolution" },
    { id: "zoo-ch27", chapterName: "Animal Adaptations" },
    { id: "zoo-ch28", chapterName: "Animal Behaviour" },
    { id: "zoo-ch29", chapterName: "Environmental Issues" },
    { id: "zoo-ch30", chapterName: "Animal Tissues" },
    { id: "zoo-ch31", chapterName: "Human Digestive System" },
    { id: "zoo-ch32", chapterName: "Human Respiratory System" },
    { id: "zoo-ch33", chapterName: "Human Excretory System" },
    { id: "zoo-ch34", chapterName: "Human Circulatory System" },
    { id: "zoo-ch35", chapterName: "Human Nervous System" },
    { id: "zoo-ch36", chapterName: "Human Endocrine System" },
    { id: "zoo-ch37", chapterName: "Human Sensory Organ" },
    { id: "zoo-ch38", chapterName: "Human Reproductive System" },
    { id: "zoo-ch39", chapterName: "Developmental Biology" },
    { id: "zoo-ch40", chapterName: "Embryonic Development in Human" },
    { id: "zoo-ch41", chapterName: "Development of Frog" },
    { id: "zoo-ch42", chapterName: "Skeletal System in Human" },
    { id: "zoo-ch43", chapterName: "Skeletal System in Rabbit" },
    { id: "zoo-ch44", chapterName: "Skeletal System in Frog" },
    { id: "zoo-ch45", chapterName: "Common Human Diseases" },
    { id: "zoo-ch46", chapterName: "Drug Abuse" },
    { id: "zoo-ch47", chapterName: "Immune System" },
    { id: "zoo-ch48", chapterName: "Application of Zoology" },
    { id: "zoo-ch49", chapterName: "Test Tube Baby" },
    { id: "zoo-ch50", chapterName: "Organ Transplant" },
    { id: "zoo-ch51", chapterName: "Vaccine" },
  ],

  botany: [
    { id: "bot-ch1", chapterName: "Taxonomy and Systematics" },
    { id: "bot-ch2", chapterName: "Virus" },
    { id: "bot-ch3", chapterName: "Kingdom Monera / Bacteria" },
    { id: "bot-ch4", chapterName: "Kingdom Fungi and Lichen" },
    { id: "bot-ch5", chapterName: "Introduction to Plant Kingdom" },
    { id: "bot-ch6", chapterName: "Algae" },
    { id: "bot-ch7", chapterName: "Bryophytes" },
    { id: "bot-ch8", chapterName: "Pteridophytes" },
    { id: "bot-ch9", chapterName: "Gymnosperm" },
    { id: "bot-ch10", chapterName: "Morphology of Angiosperm" },
    { id: "bot-ch11", chapterName: "Families of Angiosperms" },
    { id: "bot-ch12", chapterName: "Organism and Population" },
    { id: "bot-ch13", chapterName: "Eco System and Succession" },
    { id: "bot-ch14", chapterName: "Ecological Adaptations and Environmental Issues" },
    { id: "bot-ch15", chapterName: "Vegetation" },
    { id: "bot-ch16", chapterName: "Tools to Cytology and Biomolecules" },
    { id: "bot-ch17", chapterName: "Cytology" },
    { id: "bot-ch18", chapterName: "Cell Cycle and Cell Division" },
    { id: "bot-ch19", chapterName: "Mendelian Genetics (Basis of Inheritance)" },
    { id: "bot-ch20", chapterName: "Chromosomal Basis of Inheritance (Linkage and Sex Linked Inheritance)" },
    { id: "bot-ch21", chapterName: "Molecular Basis of Inheritance" },
    { id: "bot-ch22", chapterName: "Plant Anatomy" },
    { id: "bot-ch23", chapterName: "Plant Water Relation / Transport in Plant / Mineral Nutrition" },
    { id: "bot-ch24", chapterName: "Plant Photosynthesis" },
    { id: "bot-ch25", chapterName: "Plant Respiration" },
    { id: "bot-ch26", chapterName: "Plant Hormones" },
    { id: "bot-ch27", chapterName: "Plant Growth and Movements" },
    { id: "bot-ch28", chapterName: "Sexual Reproduction in Angiosperms / Embryology" },
    { id: "bot-ch29", chapterName: "Biotechnology" },
  ],

  "mental-ability-test": [

    // Unit 1: Numerical Reasoning
    { id: "mat-ch1", chapterName: "Percentage" },
    { id: "mat-ch2", chapterName: "Profit and Loss" },
    { id: "mat-ch3", chapterName: "Time and Work" },
    { id: "mat-ch4", chapterName: "Date and Calendar" },
    { id: "mat-ch5", chapterName: "Average" },
    { id: "mat-ch6", chapterName: "Ratio and Proportion" },
    { id: "mat-ch7", chapterName: "Problem on Age" },
    { id: "mat-ch8", chapterName: "Clock" },
    { id: "mat-ch9", chapterName: "Simple & Compound Interest" },
    { id: "mat-ch10", chapterName: "Partnership" },

    // Unit 2: Verbal Reasoning
    { id: "mat-ch11", chapterName: "Direction and Distance" },
    { id: "mat-ch12", chapterName: "Coding-Decoding" },
    { id: "mat-ch13", chapterName: "Ranking Order" },
    { id: "mat-ch14", chapterName: "Blood Relation" },
    { id: "mat-ch15", chapterName: "Verbal Puzzle" },
    { id: "mat-ch16", chapterName: "Cause and Effect" },
    { id: "mat-ch17", chapterName: "Assertion and Reason" },
    { id: "mat-ch18", chapterName: "Statement and Conclusion" },
    { id: "mat-ch19", chapterName: "Statement and Assumption" },
    { id: "mat-ch20", chapterName: "Statement and Argument" },
    { id: "mat-ch21", chapterName: "Situation Reaction Test" },

    // Unit 3: Logical Reasoning
    { id: "mat-ch22", chapterName: "Number Series" },
    { id: "mat-ch23", chapterName: "Verbal Series" },
    { id: "mat-ch24", chapterName: "Number Analogy" },
    { id: "mat-ch25", chapterName: "Verbal Analogy" },
    { id: "mat-ch26", chapterName: "Number Classification" },
    { id: "mat-ch27", chapterName: "Verbal Classification" },
    { id: "mat-ch28", chapterName: "Matrix & Missing Character" },
    { id: "mat-ch29", chapterName: "Logical Sequencing of Words" },
    { id: "mat-ch30", chapterName: "Continuous Pattern" },
    { id: "mat-ch31", chapterName: "Common Properties" },
    { id: "mat-ch32", chapterName: "Venn Diagram" },
    { id: "mat-ch33", chapterName: "Arithmetical Reasoning" },

    // Unit 4: Abstract Reasoning
    { id: "mat-ch34", chapterName: "Figure Series" },
    { id: "mat-ch35", chapterName: "Figure Analogy" },
    { id: "mat-ch36", chapterName: "Figure Classification" },
    { id: "mat-ch37", chapterName: "Figure Matrix" },
    { id: "mat-ch38", chapterName: "Paper Folding" },
    { id: "mat-ch39", chapterName: "Paper Cutting" },
    { id: "mat-ch40", chapterName: "Embedded Figure" },
    { id: "mat-ch41", chapterName: "Dot Situation" },
    { id: "mat-ch42", chapterName: "Cube and Dice" },
    { id: "mat-ch43", chapterName: "Mirror Image" },
    { id: "mat-ch44", chapterName: "Water Image" },
    { id: "mat-ch45", chapterName: "Pattern Completion" },
    { id: "mat-ch46", chapterName: "Figure Formation" },
    { id: "mat-ch47", chapterName: "Construction of Square & Triangle" },
    { id: "mat-ch48", chapterName: "Analytical Reasoning" },
  ],
};

export function getSubjectDisplayName(subject) {
  const nameMap = {
    physics: "Physics",
    chemistry: "Chemistry",
    zoology: "Zoology",
    botany: "Botany",
    "mental-ability-test": "Mental Ability Test",
  };
  return nameMap[subject] || subject.charAt(0).toUpperCase() + subject.slice(1);
}